//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace examenSeleccionBansi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExaman
    {
        public int idExamen { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    }
}
